version: '3.9'

services:
  db:
    image: mysql:9.0.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "${MYSQLPORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/1_create_tables.sql:ro
      - ./sql/insert_data.sql:/docker-entrypoint-initdb.d/2_insert_data.sql:ro

  app:
    build: .
    environment:
      FLASK_ENV: development
      DB_USER: ${MYSQLUSER}
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_HOST: ${MYSQLHOST}
      DB_NAME: ${MYSQL_DATABASE}
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db_data: