version: '3.9'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}    # Define a senha para o usuário root
      MYSQL_DATABASE: ${DB_NAME}             # Define o nome do banco de dados a ser criado
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/1_create_tables.sql:ro
      - ./sql/insert_data.sql:/docker-entrypoint-initdb.d/2_insert_data.sql:ro

  app:
    build: .
    environment:
      FLASK_ENV: development
      DB_USER: root                          # Use o usuário root para o banco de dados
      DB_PASSWORD: ${DB_PASSWORD}            # Senha para o root
      DB_HOST: db                            # Nome do serviço Docker para o MySQL
      DB_NAME: ${DB_NAME}                    # Nome do banco de dados
    ports:
      - "5000:5000"
    depends_on:
      - db
    volumes:
      - .:/app

volumes:
  db_data:
